#!/usr/bin/with-contenv bash
# shellcheck shell=bash

PORT=${PORT:-8080}

if [[ -z ${LSIO_NON_ROOT_USER} ]]; then
    exec \
        s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost $PORT" \
            s6-setuidgid abc taskchampion-sync-server
else
    exec \
        s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost $PORT" \
            taskchampion-sync-server
fi
